# Generated by Django 6.0.4 on 2026-05-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_material_level_material_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='level',
        ),
        migrations.RemoveField(
            model_name='material',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='material',
            name='semester',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('100', 'Level 100'), ('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400')], default='100', max_length=3)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], default='1', max_length=1)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academy.programme')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academy.course'),
            preserve_default=False,
        ),
    ]
