# Generated by Django 6.0.4 on 2026-05-09 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_material_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='material',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academy.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
